### ISSUE TITLE
The experimental results

### ISSUE THREAD

**Issue by qsc-1999** [rshaojimmy/SeqDeepFake#1]
Hello, the work you proposed is very interesting. I used your open code for training, but the experimental results cannot reach the results in the paper, especially in components on r50, which is 10 points lower than that in the paper. May I ask why?

**Comment by TianxingWu** [comment]
Hi @qsc-1999 
Thanks for your feedback. I suggest that you test with the provided checkpoints and compare with benchmark results first to check whether your pipeline, dataset and environment is right.
Although there could be some randomness in the training procedure, we have not encounter such amount of fluctuate during our experiments. Could you please share the `.sh` file you used to produce the results?

**Comment by ZXX-Coding** [comment]
> Hi [@qsc-1999](https://github.com/qsc-1999) Thanks for your feedback. I suggest that you test with the provided checkpoints and compare with benchmark results first to check whether your pipeline, dataset and environment is right. Although there could be some randomness in the training procedure, we have not encounter such amount of fluctuate during our experiments. Could you please share the `.sh` file you used to produce the results?

Hello,
I encountered a similar issue during my experiments. When using ResNet-50 on the attribute dataset, I was able to reproduce the results reported in the paper. However, when switching to the component dataset, the performance dropped by around 10 points. Could it be that the two ResNet-50 model files are different?

Below is the .sh script I used for training:
LOGNAME=log$(date +"%Y%m%d_%H%M%S")
CONFIG='./configs/r34.json'
DATA_DIR='/data/zxx/Seq-DeepFake'
DATASET_NAME='facial_attributes'
RESULTS_DIR='./results'

HOST='127.0.0.1'
PORT='12345'
NUM_GPU=1

python train.py \
--log_name ${LOGNAME} \
--cfg ${CONFIG} \
--data_dir ${DATA_DIR} \
--dataset_name ${DATASET_NAME} \
--val_epoch 10 \
--model_save_epoch 5 \
--manual_seed 777 \
--dist-url tcp://${HOST}:${PORT} \
--world_size $NUM_GPU \
--rank 0 \
--launcher none \
--results_dir ${RESULTS_DIR}
Would you like me to help double-check this script or the config file for potential issues?

**Comment by ZXX-Coding** [comment]
> > Hi [@qsc-1999](https://github.com/qsc-1999) Thanks for your feedback. I suggest that you test with the provided checkpoints and compare with benchmark results first to check whether your pipeline, dataset and environment is right. Although there could be some randomness in the training procedure, we have not encounter such amount of fluctuate during our experiments. Could you please share the `.sh` file you used to produce the results?
> 
> Hello, I encountered a similar issue during my experiments. When using ResNet-50 on the attribute dataset, I was able to reproduce the results reported in the paper. However, when switching to the component dataset, the performance dropped by around 10 points. Could it be that the two ResNet-50 model files are different?
> 
> Below is the .sh script I used for training: LOGNAME=log$(date +"%Y%m%d_%H%M%S") CONFIG='./configs/r34.json' DATA_DIR='/data/zxx/Seq-DeepFake' DATASET_NAME='facial_attributes' RESULTS_DIR='./results'
> 
> HOST='127.0.0.1' PORT='12345' NUM_GPU=1
> 
> python train.py --log_name ${LOGNAME} --cfg ${CONFIG} --data_dir ${DATA_DIR} --dataset_name ${DATASET_NAME} --val_epoch 10 --model_save_epoch 5 --manual_seed 777 --dist-url tcp://${HOST}:${PORT} --world_size $NUM_GPU --rank 0 --launcher none --results_dir ${RESULTS_DIR} Would you like me to help double-check this script or the config file for potential issues?

"optimizer": {
    "batch_size": 32,
    "lr_backbone": 1e-4,
    "lr": 1e-3,
    "epochs": 170,
    "warmup": true,
    "warmup_epochs": 20,
    "lr_milestones": [70, 120],
    "start_epoch": 0,
    "weight_decay": 1e-4,
    "clip_max_norm": 0.1
}
Has this part changed?
