### ISSUE TITLE
Sequential DeepFake 

### ISSUE THREAD

**Issue by zimyang** [rshaojimmy/SeqDeepFake#2]
May I ask for a demo code of manipulating facial componnets with StyleMapGAN on the CelebAMask-HQ dataset? Thank you very much.

**Comment by rshaojimmy** [comment]
Hi,

We just follow the code of StyleMapGAN from https://github.com/naver-ai/StyleMapGAN

Masks of facial components are directly borrowed from CelebAMask-HQ dataset. Details can be referred to our paper.

Thanks.

**Comment by zimyang** [comment]
I have tried to re-implement facial manipulation with StyleMapGAN on CelebAMask-HQ. But the amount of available images is only 500. 
(Image Directory: original_test_path = f"{dataset_folder}/raw_images/test/images"). 
It is too few to construct a DeepFake dataset.

**Comment by rshaojimmy** [comment]
We have used all splits of CelebAMask-HQ (including train/val/test splits) for facial manipulation based on a minor modified StyleMapGAN code. After that, we filter generated images based on GIQA.

The number of manipulation images is provided in our paper.

**Comment by zimyang** [comment]
Where can I get the GT_labels of train/val set of CelebAMask-HQ? The GT_labels on the download script only contain masks of test set. Shall I merge the masks of each image based on the annotations of CelebAMask-HQ?

**Comment by rshaojimmy** [comment]
We download CelebAMask-HQ from here: http://mmlab.ie.cuhk.edu.hk/projects/CelebA/CelebAMask_HQ.html

It contains 30000 images. Each image is provided with masks for all facial components.

We use all of them to generate manipulation images, which are then split into train/val/test splits.

**Comment by zimyang** [comment]
I see : )
Thank you so much!

**Comment by rshaojimmy** [comment]
Sure. No problem.
