### ISSUE TITLE
facial attribute dataset

### ISSUE THREAD

**Issue by DeidaraYang** [rshaojimmy/SeqDeepFake#3]
Thanks for this creative work! I wondering if you can supplement all original faces wiithout forgery in facial attribute dataset as I do not find the corresponding original face in the ffhq dataset.

**Comment by rshaojimmy** [comment]
Hi Thanks for your interest in our work!

I am sorry that we have not stored the original faces corresponding to each forgery counterpart. But you may refer to the original faces in our dataset as they all come from ffhq dataset.
