### ISSUE TITLE
About the Recovering Sequential DeepFake code

### ISSUE THREAD

**Issue by 18363525201** [rshaojimmy/SeqDeepFake#6]
I am sorry to disturb you. I am very interested in your paper. Can you provide some code for recovery. Thank you very much

**Comment by guishengzhanga** [comment]
Hello, have you obtained the code for recovery?

**Comment by 18363525201** [comment]
> Hello, have you obtained the code for recovery?

No ，I'm waiting, too

**Comment by guishengzhanga** [comment]
> > Hello, have you obtained the code for recovery?
> 
> No ，I'm waiting, too

May be we can discuss it through other ways, like email or WeChat if you want.

**Comment by guishengzhanga** [comment]
> > Hello, have you obtained the code for recovery?
> 
> No ，I'm waiting, too

May be we can discuss it through other ways, like WeChat. My WeChat is: zgs178533
